"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

APP = ["quince/main.py"]
DATA_FILES = [("quince", ["quince/assets"]),
              ]
OPTIONS = {"iconfile": "quince/assets/favicon.icns"}
PACKAGES = ["quince",
            "quince.components",
            "quince.ui",
            "quince.ui.common",
            "quince.ui.opponents",
            "quince.ui.player",
            "quince.ui.score_report",
            "quince.ui.table",
            "quince.ui.top_menu"
            ]

version = {}
with open("quince/version.py") as fp:
    exec(fp.read(), version)
VERSION = version["__version__"]

setup(
    name="Quince",
    version=VERSION,
    description="Classic Spanish card game.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Dan Liberatori",
    author_email="daniel.liberatori@gmail.com",
    url="http://www.danliberatori.com",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    packages=PACKAGES
)
